import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
# Load image
img = Image.open("shashank.jpeg")

# Convert to NumPy array
img_array = np.array(img)

print("Image Shape:", img_array.shape)
plt.imshow(img_array)
plt.title("Original Image")
plt.show()
gray = np.mean(img_array, axis=2)
plt.imshow(gray, cmap='gray')
plt.title("Grayscale Image")
plt.show()
flip_h = np.fliplr(img_array)
plt.imshow(flip_h)
plt.title("flip Image")
plt.show()
flip_v = np.flipud(img_array)
plt.imshow(flip_v)
plt.title("flip Image")
plt.show()
cropped = img_array[100:300, 100:300]
plt.imshow(cropped)
plt.title("Cropped Image")
plt.show()
red = img_array[:,:,0]
plt.imshow(red)
plt.title("Red Image")
plt.show()
green = img_array[:,:,1]
plt.imshow(green)
plt.title("Green Image")
plt.show()
blue = img_array[:,:,2]
plt.imshow(blue)
plt.title("Blue Image")
plt.show()
bright = img_array + 50
bright = np.clip(bright, 0, 255)
plt.imshow(bright.astype(np.uint8))
plt.title("Brightened Image")
plt.show()
contrast = img_array * 1.5
contrast = np.clip(contrast, 0, 255)
plt.imshow(contrast.astype(np.uint8))
plt.title("High Contrast")
plt.show()
log_img = np.log1p(img_array)
plt.imshow(log_img.astype(np.uint8))
plt.title("log image")
plt.show()
sqrt_img = np.sqrt(img_array)
plt.imshow(sqrt_img.astype(np.uint8))
plt.title("sqrt image")
plt.show()
inverted = np.bitwise_not(img_array)
plt.imshow(inverted)
plt.title("Inverted Image")
plt.show()
binary = img_array > 128
plt.imshow(binary)
plt.title("Binary Image")
plt.show()
sorted_pixels = np.sort(img_array, axis=None)
bright_pixels = np.sum(img_array > 200)
print("Bright Pixels:", bright_pixels)
adjusted = img_array + np.array([20, 0, 0])  # increase red
plt.imshow(np.clip(adjusted, 0, 255).astype(np.uint8))
plt.title("Red Enhanced")
plt.show()
stacked = np.hstack((img_array, flip_h))
plt.imshow(stacked)
plt.title("Stacked Image")
plt.show()
copy_img = img_array.copy()
plt.imshow(copy_img)
plt.title("copy Image")
plt.show()
view_img = img_array.view()
plt.imshow(view_img)
plt.title("view Image")
plt.show()
